### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by matteocrippa** [IBM-Swift/Kitura-sys#1]
Trying to build under **DEVELOPMENT-SNAPSHOT-2016-02-08-a** I noticed this error

```
Linking Library:  .build/debug/LoggerAPI.a
Compiling Swift Module 'KituraSys' (4 sources)
<unknown>:0: error: module 'Dispatch' requires feature 'blocks'
<unknown>:0: error: could not build Objective-C module 'Dispatch'
<unknown>:0: error: module 'Dispatch' requires feature 'blocks'
<unknown>:0: error: could not build Objective-C module 'Dispatch'
<unknown>:0: error: module 'Dispatch' requires feature 'blocks'
<unknown>:0: error: could not build Objective-C module 'Dispatch'
<unknown>:0: error: module 'Dispatch' requires feature 'blocks'
<unknown>:0: error: could not build Objective-C module 'Dispatch'
<unknown>:0: error: build had 1 command failures
error: exit(1): ["/root/swift-DEVELOPMENT-SNAPSHOT-2016-02-08-a-ubuntu15.10/usr/bin/swift-build-tool", "-f", "/data/Kitura-sys/.build/debug/Kitura-Sys.o/llbuild.yaml"]
```

**Comment by rfdickerson** [comment]
Currently, in order for code that uses libDispatch to compile link correctly, you need to do a swift build with the -Xcc -fblocks and -Xlinker -ldispatch. The Makefile simplifies this for you.

**Comment by matteocrippa** [comment]
@rfdickerson thx, I confirm you that using
```
swift build -Xcc -fblocks -Xlinker -ldispatch
```

it works fine.

But I have no makefile inside this repo, is this correct? As far as I remember there is only one in [KituraNet](https://github.com/IBM-Swift/Kitura-net/blob/master/Makefile-client), but dunno if it is the one you are referring to.

**Comment by rfdickerson** [comment]
Ah yes, please copy and rename Packages/KituraNet/Makefile-client to Makefile in your project root path.

**Comment by dfirsht** [comment]
@rfdickerson The makefile is set up to build the entire project not a single module so it will not work in building swift. @matteocrippa For now, just use the single command.

**Comment by Ujjawal2** [comment]
![screen shot 2016-06-10 at 11 39 36 am](https://cloud.githubusercontent.com/assets/10569915/15955598/1780c842-2f00-11e6-9c5f-9c6286e863f8.png)
Please help

**Comment by vadimeisenbergibm** [comment]
@Ujjawal2 You are running the latest swift compiler version which is not supported yet by Kitura.

Please use DEVELOPMENT-SNAPSHOT-2016-05-09-a with develop branch and DEVELOPMENT-SNAPSHOT-2016-05-03-a with master, you can download them from https://swift.org/download/#snapshots.

**Comment by Kam21** [comment]
Hi 
i am trying to create a docker image Docker file

Docker File:
```
FROM ibmcom/kitura-ubuntu:latest
USER root
ENV PATH /usr/bin:$PATH

RUN mkdir -p /SwiftClientApi

WORKDIR /SwiftClientApi

ADD . /SwiftClientApi

# Print Installed Swift Version
#RUN swift --version

RUN swift build -Xcc -fblocks -Xlinker -ldispatch
#RUN swift build

EXPOSE 8090
CMD .build/debug/ClientApi
```


getting similar issue as above with dev snapshot:


```
Removing intermediate container 666b67a68112
Step 7 : RUN swift build -Xcc -fblocks -Xlinker -ldispatch
 ---> Running in a2021b9357e9
Compile CHttpParser utils.c
Compile CHttpParser http_parser.c
Compile Swift Module 'KituraTemplateEngine' (1 sources)
Compile Swift Module 'SwiftyJSON' (2 sources)
Compile Swift Module 'Socket' (3 sources)
Compile Swift Module 'LoggerAPI' (1 sources)
clang: warning: argument unused during compilation: '-Xcc'
clang: warning: argument unused during compilation: '-Xcc'
Linking CHttpParser
/usr/bin/ld: error: cannot find -ldispatch
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<unknown>:0: error: build had 1 command failures
swift-build: error: exit(1): /root/swift-DEVELOPMENT-SNAPSHOT-2016-06-20-a-ubuntu14.04/usr/bin/swift-build-tool -f /SwiftClientApi/.build/debug.yaml
The command '/bin/sh -c swift build -Xcc -fblocks -Xlinker -ldispatch' returned a non-zero code: 1
```

Can someone help ?
